environment:
  matrix:
  - nodejs_version: "12"
install:
  - ps: |
      try {
      Install-Product node $env:nodejs_version $env:platform
      } catch {
      echo "Unable to install node $env:nodejs_version, trying update..."
      Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
      }
  - yarn install --ignore-engines
test_script:
  - node --version
  - yarn test
build: off

before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb testdb
services:
  - postgresql10